// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB99NcfcAYb3qjfq5chYR-k9lwQUDp4uTw',
    appId: '1:383443993578:web:cb8cfc8c41929b90726893',
    messagingSenderId: '383443993578',
    projectId: 'laptopshop-5b492',
    authDomain: 'laptopshop-5b492.firebaseapp.com',
    storageBucket: 'laptopshop-5b492.firebasestorage.app',
    measurementId: 'G-HYX626Q87B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgk8AXnY2UTTehicUhTliQ2ewAJmeG1_c',
    appId: '1:383443993578:android:b93ac1b8fcf40674726893',
    messagingSenderId: '383443993578',
    projectId: 'laptopshop-5b492',
    storageBucket: 'laptopshop-5b492.firebasestorage.app',
  );
}
